apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: audio-model
  namespace: seldon
spec:
  name: audio
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          image: audio-image
    graph:
      name: classifier
    name: default
    replicas: 1
